[package]
name = "rust-to-c"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"
links = "confuse"

[dependencies]
libc = "0.1"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3.11"
